import {runFantasyBulk,compareFantasyRuns} from './player-bulk.ts';
import type {FantasyOptions} from './player-engine.ts';
import {simulateGameV2,type GameInputV2} from './engine.ts';
import type {EmpiricalProfile} from './empirical.ts';
// Shared V1 summarizer has a JS implementation; only team/game values are summarized here.
// @ts-expect-error Existing JS utility has no declaration.
import {summarize} from '../../../public/simulation/statistics.js';
type Request={game:GameInputV2;count:number;seed:string;trace:boolean;profile?:EmpiricalProfile;fantasy?:Omit<FantasyOptions,'seed'|'empirical'>;compare?:boolean};
// Browser DedicatedWorker, separate from the project's Cloudflare service-worker globals.
const scope=self as unknown as {onmessage:(event:{data:Request})=>void;postMessage:(value:unknown)=>void};
scope.onmessage=(event:{data:Request})=>{try{const {game,count,seed,trace,profile}=event.data;if(!Number.isInteger(count)||count<1||count>10000||typeof seed!=='string'||seed.length>100)throw Error('Choose 1–10,000 games and a short seed.');if(event.data.fantasy){if(!profile)throw Error('Empirical profile required');const opts={...event.data.fantasy,seed,empirical:profile,debugTrace:trace};const result=runFantasyBulk(game,opts,count,done=>scope.postMessage({type:'progress',done,count,stage:event.data.compare?'Personnel':'Simulation'}));if(event.data.compare){const base=runFantasyBulk(game,{...opts,engine:'base',influence:0},count,done=>scope.postMessage({type:'progress',done,count,stage:'Base comparison'}));scope.postMessage({type:'result',data:{...result,comparisonRuntimeMs:result.runtimeMs+base.runtimeMs,comparison:compareFantasyRuns(base,result),base}});}else scope.postMessage({type:'result',data:result});return;}const start=performance.now();const home:number[]=[],away:number[]=[],total:number[]=[],margin:number[]=[];let example:ReturnType<typeof simulateGameV2>|undefined;let plays=0,possessions=0,yards=0,turnovers=0,passes=0,rushes=0;for(let i=0;i<count;i++){const r=simulateGameV2(game,{seed:`${seed}:${i}`,debugTrace:trace&&i===0,empirical:profile});if(!r.completed)throw Error('Play limit reached; incomplete run discarded.');if(i===0)example=r;home.push(r.finalState.scoreHome);away.push(r.finalState.scoreAway);total.push(r.totalPoints);margin.push(r.homeScoreDifferential);for(const t of Object.values(r.teams)){plays+=t.offensivePlays;possessions+=t.possessions;yards+=t.passingYards+t.rushingYards-t.sackYards;turnovers+=t.turnovers;passes+=t.passAttempts;rushes+=t.rushingAttempts;}if((i+1)%100===0)scope.postMessage({type:'progress',done:i+1,count});}scope.postMessage({type:'result',data:{metadata:{model_version:example!.modelVersion,engine:profile?'legacy_empirical':'foundation',personnel_influence:0,personnel_configuration:null,madden_snapshot:null,roster_snapshot:null,empirical_version:profile?.version??null,empirical_profile:profile?.profileId??null,seed},count,seed,home:summarize(home),away:summarize(away),total:summarize(total),margin:summarize(margin),plays:plays/count/2,possessions:possessions/count/2,yards:yards/count/2,turnovers:turnovers/count,passes:passes/count/2,rushes:rushes/count/2,runtimeMs:performance.now()-start,example}});}catch(error){scope.postMessage({type:'error',message:error instanceof Error?error.message:'Simulation failed'});}};
