import {empiricalPass,empiricalYards,paceContext,validateProfile,type EmpiricalProfile} from './empirical.ts';
import {random,fingerprint,type Random} from '../../../public/simulation/random.js';
export const MODEL_VERSION='V2.0-A';
export type PlayType='RUN'|'PASS'|'PUNT'|'FIELD_GOAL';
export type ResultType='RUN'|'COMPLETE'|'INCOMPLETE'|'SACK'|'INTERCEPTION'|'FUMBLE'|'PUNT'|'FG_GOOD'|'FG_MISS';
export type DriveResult='TOUCHDOWN'|'FIELD_GOAL'|'MISSED_FIELD_GOAL'|'PUNT'|'TURNOVER'|'DOWNS'|'SAFETY'|'END_HALF'|'END_GAME'|'PLAY_LIMIT';
export interface TeamInputs {passRate:number;completionRate:number;sackRate:number;interceptionRate:number;fumbleRate:number;runMean:number;runSd:number;completionMean:number;completionSd:number;}
export interface GameInputV2 {gameId:string;homeTeam:string;awayTeam:string;homeTeamInputs:Partial<TeamInputs>&{passRate:number};awayTeamInputs:Partial<TeamInputs>&{passRate:number};inputsTimestamp:string;}
export interface Rules {normalPace:number;hurryPace:number;drainPace:number;lateSeconds:number;trailingPassAdjustment:number;leadingPassAdjustment:number;longDistanceAdjustment:number;thirdDownAdjustment:number;fourthGoDistance:number;fourthGoField:number;maxFieldGoalDistance:number;puntYards:number;startField:number;fgShort:number;fgMedium:number;fgLong:number;}
export const DEFAULT_RULES:Rules={normalPace:29,hurryPace:13,drainPace:38,lateSeconds:300,trailingPassAdjustment:.12,leadingPassAdjustment:-.15,longDistanceAdjustment:.1,thirdDownAdjustment:.08,fourthGoDistance:2,fourthGoField:55,maxFieldGoalDistance:57,puntYards:43,startField:30,fgShort:.95,fgMedium:.85,fgLong:.65};
export const DEFAULT_TEAM:Omit<TeamInputs,'passRate'>={completionRate:.65,sackRate:.065,interceptionRate:.022,fumbleRate:.006,runMean:4.3,runSd:4.5,completionMean:10.8,completionSd:8};
export interface GameState {gameId:string;homeTeam:string;awayTeam:string;possession:string;openingReceiver:string;quarter:number;clock:number;scoreHome:number;scoreAway:number;field:number;down:number;distance:number;driveNumber:number;playNumber:number;possessionNumber:number;status:'PLAYING'|'HALFTIME'|'FINAL'|'PLAY_LIMIT';overtime:false;clockRunning:boolean;}
export interface Outcome {playType:PlayType;resultType:ResultType;yards:number;duration:number;}
export interface Transition {state:GameState;elapsed:number;deadTime:number;yards:number;firstDown:boolean;touchdown:boolean;safety:boolean;clockStops:boolean;driveResult?:DriveResult;}
export interface Drive {number:number;team:string;startField:number;plays:number;yards:number;seconds:number;result:DriveResult;}
export interface TeamTotals {offensivePlays:number;passPlays:number;rushPlays:number;passAttempts:number;completions:number;rushingAttempts:number;passingYards:number;rushingYards:number;sacks:number;sackYards:number;interceptions:number;turnovers:number;firstDowns:number;possessions:number;touchdowns:number;fieldGoals:number;safeties:number;}
export interface Options {seed:string;maxPlays?:number;debugTrace?:boolean;rules?:Partial<Rules>;empirical?:EmpiricalProfile;resolve?:(type:PlayType,state:GameState,team:TeamInputs,rng:Random,rules:Rules,profile?:EmpiricalProfile)=>Outcome;onPlay?:(before:GameState,outcome:Outcome,transition:Transition)=>void;}
const clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
const other=(s:GameState)=>s.possession===s.homeTeam?s.awayTeam:s.homeTeam;
export function scoreDifferential(s:GameState){return s.possession===s.homeTeam?s.scoreHome-s.scoreAway:s.scoreAway-s.scoreHome;}
export function assertState(s:GameState){if(!Number.isInteger(s.quarter)||s.quarter<1||s.quarter>4||!Number.isFinite(s.clock)||s.clock<0||s.clock>900||!Number.isInteger(s.down)||s.down<1||s.down>4||!Number.isInteger(s.field)||s.field<1||s.field>99||!Number.isInteger(s.distance)||s.distance<1||s.distance>100-s.field||![s.homeTeam,s.awayTeam].includes(s.possession)||[s.scoreHome,s.scoreAway].some(x=>!Number.isInteger(x)||x<0))throw Error('Invalid game state');}
export function openingState(g:GameInputV2,receiver=g.awayTeam,r:Rules=DEFAULT_RULES):GameState {const s:GameState={gameId:g.gameId,homeTeam:g.homeTeam,awayTeam:g.awayTeam,possession:receiver,openingReceiver:receiver,quarter:1,clock:900,scoreHome:0,scoreAway:0,field:r.startField,down:1,distance:Math.min(10,100-r.startField),driveNumber:1,playNumber:0,possessionNumber:1,status:'PLAYING',overtime:false,clockRunning:false};assertState(s);return s;}
function newPossession(s:GameState,team:string,field:number):GameState{return {...s,possession:team,field:clamp(field,1,99),down:1,distance:Math.min(10,100-clamp(field,1,99)),driveNumber:s.driveNumber+1,possessionNumber:s.possessionNumber+1,clockRunning:false};}
function award(s:GameState,team:string,points:number){return {...s,scoreHome:s.scoreHome+(team===s.homeTeam?points:0),scoreAway:s.scoreAway+(team===s.awayTeam?points:0)};}
function boundary(s:GameState):GameState {if(s.clock>0)return s;if(s.quarter===4)return {...s,status:'FINAL',clockRunning:false};if(s.quarter===2)return {...s,status:'HALFTIME',clockRunning:false};return {...s,quarter:s.quarter+1,clock:900,clockRunning:false};}
export function startSecondHalf(s:GameState,r:Rules=DEFAULT_RULES):GameState {if(s.status!=='HALFTIME')throw Error('Not halftime');return newPossession({...s,quarter:3,clock:900,status:'PLAYING'},s.openingReceiver===s.homeTeam?s.awayTeam:s.homeTeam,r.startField);}
export function pace(s:GameState,r:Rules=DEFAULT_RULES){return s.quarter===4&&s.clock<=r.lateSeconds?(scoreDifferential(s)<0?r.hurryPace:scoreDifferential(s)>0?r.drainPace:r.normalPace):r.normalPace;}
/** Drain between snaps before choosing the next play. No play occurs if the quarter expires. */
export function advanceBetweenPlays(s:GameState,r:Rules=DEFAULT_RULES){const deadTime=pace(s,r),elapsed=s.clockRunning?Math.min(s.clock,deadTime):0;const next=boundary({...s,clock:s.clock-elapsed});return {state:next,elapsed,deadTime,expired:elapsed>0&&elapsed===s.clock};}
export function passProbability(s:GameState,t:TeamInputs,r:Rules=DEFAULT_RULES){return clamp(t.passRate+(s.distance>=8?r.longDistanceAdjustment:0)+(s.down>=3?r.thirdDownAdjustment:0)+(s.quarter===4&&s.clock<=r.lateSeconds?(scoreDifferential(s)<0?r.trailingPassAdjustment:scoreDifferential(s)>0?r.leadingPassAdjustment:0):0),.05,.95);}
export function selectPlay(s:GameState,t:TeamInputs,rng:Random,r:Rules=DEFAULT_RULES,profile?:EmpiricalProfile):PlayType {const probability=()=>profile?empiricalPass(s,t,profile):passProbability(s,t,r);const fg=117-s.field;if((s.down===4||s.clock<=8&&[2,4].includes(s.quarter))){if(s.down===4&&s.distance<=r.fourthGoDistance&&s.field>=r.fourthGoField)return rng.uniform()<probability()?'PASS':'RUN';if(fg<=r.maxFieldGoalDistance)return 'FIELD_GOAL';if(s.down===4&&!(s.quarter===4&&s.clock<=r.lateSeconds&&scoreDifferential(s)<0))return 'PUNT';}return rng.uniform()<probability()?'PASS':'RUN';}
export function resolvePlay(type:PlayType,s:GameState,t:TeamInputs,rng:Random,r:Rules=DEFAULT_RULES,profile?:EmpiricalProfile):Outcome {const normal=(mean:number,sd:number,min:number,max:number)=>clamp(Math.round(mean+sd*rng.normal()),min,max);if(type==='PUNT')return {playType:type,resultType:'PUNT',yards:r.puntYards,duration:7};if(type==='FIELD_GOAL'){const distance=117-s.field;return {playType:type,resultType:rng.uniform()<(distance<=39?r.fgShort:distance<=49?r.fgMedium:r.fgLong)?'FG_GOOD':'FG_MISS',yards:0,duration:5};}if(type==='RUN')return {playType:type,resultType:rng.uniform()<t.fumbleRate?'FUMBLE':'RUN',yards:profile?empiricalYards('run',profile,rng):normal(t.runMean,t.runSd,-8,60),duration:6};if(rng.uniform()<t.sackRate)return {playType:type,resultType:'SACK',yards:-normal(6,2,1,15),duration:6};if(rng.uniform()<t.interceptionRate)return {playType:type,resultType:'INTERCEPTION',yards:normal(12,10,0,60),duration:6};if(rng.uniform()>=t.completionRate)return {playType:type,resultType:'INCOMPLETE',yards:0,duration:5};return {playType:type,resultType:'COMPLETE',yards:profile?empiricalYards('complete',profile,rng):normal(t.completionMean,t.completionSd,-5,80),duration:6};}
export function applyOutcome(state:GameState,o:Outcome,r:Rules=DEFAULT_RULES):Transition {
 assertState(state);if(state.status!=='PLAYING'||state.clock<=0)throw Error('Game not ready for snap');
 const allowed:Record<PlayType,ResultType[]>={RUN:['RUN','FUMBLE'],PASS:['COMPLETE','INCOMPLETE','SACK','INTERCEPTION'],PUNT:['PUNT'],FIELD_GOAL:['FG_GOOD','FG_MISS']};
 if(!allowed[o.playType]?.includes(o.resultType)||!Number.isInteger(o.yards)||!Number.isFinite(o.duration)||o.duration<=0||o.duration>30||o.resultType==='INCOMPLETE'&&o.yards!==0||o.resultType==='SACK'&&o.yards>=0)throw Error('Invalid outcome');
 const elapsed=Math.min(state.clock,o.duration);let s={...state,clock:state.clock-elapsed,playNumber:state.playNumber+1};let driveResult:DriveResult|undefined;let firstDown=false,touchdown=false,safety=false;
 let yards=['RUN','COMPLETE','SACK','FUMBLE'].includes(o.resultType)?clamp(o.yards,-state.field,100-state.field):0;
 const endpoint=state.field+o.yards;const defense=other(state);
 let nextTeam:string|undefined,nextField=0;
 if(o.resultType==='PUNT'){driveResult='PUNT';nextTeam=defense;nextField=endpoint>=100?20:100-endpoint;}
 else if(o.resultType==='FG_GOOD'){s=award(s,state.possession,3);driveResult='FIELD_GOAL';nextTeam=defense;nextField=r.startField;}
 else if(o.resultType==='FG_MISS'){driveResult='MISSED_FIELD_GOAL';nextTeam=defense;nextField=Math.max(20,107-state.field);}
 else if(o.resultType==='INTERCEPTION'||o.resultType==='FUMBLE'){driveResult='TURNOVER';nextTeam=defense;nextField=endpoint>=100?20:100-clamp(endpoint,1,99);}
 else if(endpoint>=100){s=award(s,state.possession,7);touchdown=true;firstDown=true;driveResult='TOUCHDOWN';nextTeam=defense;nextField=r.startField;}
 else if(endpoint<=0){s=award(s,defense,2);safety=true;driveResult='SAFETY';nextTeam=defense;nextField=r.startField;}
 else {s.field=endpoint;if(o.yards>=state.distance){firstDown=true;s.down=1;s.distance=Math.min(10,100-endpoint);}else if(state.down===4){s.distance=state.distance-o.yards;driveResult='DOWNS';nextTeam=defense;nextField=100-endpoint;}else{s.down++;s.distance=state.distance-o.yards;}}
 s.clockRunning=!driveResult&&o.resultType!=='INCOMPLETE';
 // A final-play score counts, but no phantom possession is created after the half/game ends.
 const halfEnd=s.clock===0&&[2,4].includes(s.quarter);
 if(nextTeam&&!halfEnd)s=newPossession(s,nextTeam,nextField);
 if(halfEnd&&!driveResult)driveResult=s.quarter===2?'END_HALF':'END_GAME';
 s=boundary(s);assertState(s);
 return {state:s,elapsed,deadTime:o.duration,yards,firstDown,touchdown,safety,clockStops:!s.clockRunning,driveResult};
}
function totals():TeamTotals{return {offensivePlays:0,passPlays:0,rushPlays:0,passAttempts:0,completions:0,rushingAttempts:0,passingYards:0,rushingYards:0,sacks:0,sackYards:0,interceptions:0,turnovers:0,firstDowns:0,possessions:0,touchdowns:0,fieldGoals:0,safeties:0};}
function validate(g:GameInputV2,o:Options,r:Rules){if([g.gameId,g.homeTeam,g.awayTeam].some(x=>typeof x!=='string'||!x.trim())||g.homeTeam===g.awayTeam||!Number.isFinite(Date.parse(g.inputsTimestamp))||typeof o.seed!=='string'||!o.seed)throw Error('Invalid game input/seed');for(const input of [g.homeTeamInputs,g.awayTeamInputs]){if(!input||!Number.isFinite(input.passRate))throw Error('Team pass rate required');const t={...DEFAULT_TEAM,...input};for(const [k,v]of Object.entries(t)){if(!Number.isFinite(v))throw Error('Nonfinite team input');if(k.endsWith('Rate')&&(v<0||v>1))throw Error('Probability out of range');if(k.endsWith('Sd')&&(v<0||v>30))throw Error('Invalid spread');if(k.endsWith('Mean')&&(v<0||v>30))throw Error('Invalid mean');}}for(const [k,v]of Object.entries(r)){if(!Number.isFinite(v))throw Error('Invalid rules');if(k.startsWith('fg')&&(v<0||v>1))throw Error('Invalid kick probability');}if(!Number.isInteger(r.startField)||r.startField<1||r.startField>99||[r.normalPace,r.hurryPace,r.drainPace].some(v=>v<0||v>40)||!Number.isInteger(r.puntYards)||r.puntYards<1||r.puntYards>80)throw Error('Invalid field/pace');if(!Number.isInteger(r.fourthGoDistance)||r.fourthGoDistance<0||r.fourthGoDistance>10||!Number.isInteger(r.fourthGoField)||r.fourthGoField<1||r.fourthGoField>99||r.lateSeconds<0||r.lateSeconds>900||r.maxFieldGoalDistance<17||r.maxFieldGoalDistance>70||[r.trailingPassAdjustment,r.leadingPassAdjustment,r.longDistanceAdjustment,r.thirdDownAdjustment].some(v=>Math.abs(v)>1))throw Error('Invalid decision rules');if(!Number.isInteger(o.maxPlays??500)||(o.maxPlays??500)<1||(o.maxPlays??500)>10000)throw Error('Invalid max plays');}
export function simulateGameV2(g:GameInputV2,options:Options){
 const rules={...DEFAULT_RULES,...options.rules};validate(g,options,rules);if(options.empirical)validateProfile(options.empirical);const modelVersion=options.empirical?.version||MODEL_VERSION;const rng=random(`${modelVersion}|${options.seed}`);const inputs={[g.homeTeam]:{...DEFAULT_TEAM,...g.homeTeamInputs},[g.awayTeam]:{...DEFAULT_TEAM,...g.awayTeamInputs}};
 let state=openingState(g,rng.uniform()<.5?g.homeTeam:g.awayTeam,rules);const teams={[g.homeTeam]:totals(),[g.awayTeam]:totals()};const drives:Drive[]=[];const trace:unknown[]=[];let seconds=0,operationalSeconds=0;
 let drive={number:state.driveNumber,team:state.possession,startField:state.field,plays:0,yards:0,seconds:0};teams[state.possession].possessions++;
 const close=(result:DriveResult)=>{drives.push({...drive,result});};
 const start=()=>{drive={number:state.driveNumber,team:state.possession,startField:state.field,plays:0,yards:0,seconds:0};teams[state.possession].possessions++;};
 while(state.status!=='FINAL'){
  if(state.playNumber>=(options.maxPlays??500)){state={...state,status:'PLAY_LIMIT'};close('PLAY_LIMIT');break;}
  const pre=advanceBetweenPlays(state,options.empirical?{...rules,normalPace:options.empirical.pace[paceContext(state)]?.seconds??rules.normalPace,hurryPace:options.empirical.pace.trail?.seconds??rules.hurryPace,drainPace:options.empirical.pace.lead?.seconds??rules.drainPace}:rules);seconds+=pre.elapsed;operationalSeconds+=pre.deadTime;drive.seconds+=pre.elapsed;state=pre.state;
  if(pre.expired){if(state.status==='HALFTIME'){close('END_HALF');state=startSecondHalf(state,rules);start();}else if(state.status==='FINAL'){close('END_GAME');break;}continue;}
  const before={...state};const type=selectPlay(state,inputs[state.possession],rng,rules,options.empirical);const outcome=(options.resolve||resolvePlay)(type,state,inputs[state.possession],rng,rules,options.empirical);const step=applyOutcome(state,outcome,rules);state=step.state;seconds+=step.elapsed;operationalSeconds+=step.deadTime;drive.plays++;drive.yards+=step.yards;drive.seconds+=step.elapsed;
  const t=teams[before.possession];if(type==='RUN'||type==='PASS')t.offensivePlays++;if(outcome.playType==='RUN'){t.rushPlays++;t.rushingAttempts++;t.rushingYards+=step.yards;}if(outcome.playType==='PASS'){t.passPlays++;if(outcome.resultType==='SACK'){t.sacks++;t.sackYards-=step.yards;}else t.passAttempts++;if(outcome.resultType==='COMPLETE'){t.completions++;t.passingYards+=step.yards;}if(outcome.resultType==='INTERCEPTION')t.interceptions++;}if(step.driveResult==='TURNOVER')t.turnovers++;if(step.firstDown)t.firstDowns++;if(step.touchdown)t.touchdowns++;if(outcome.resultType==='FG_GOOD')t.fieldGoals++;if(step.safety)teams[other(before)].safeties++;
  options.onPlay?.(before,outcome,step);
  if(options.debugTrace)trace.push({before,outcome,...step});
  if(step.driveResult)close(step.driveResult);
  if(state.status==='HALFTIME'){state=startSecondHalf(state,rules);start();}else if(state.status==='PLAYING'&&state.driveNumber!==before.driveNumber)start();
 }
 const differential=state.scoreHome-state.scoreAway;
 return {modelVersion,runId:fingerprint({g,seed:options.seed,rules,maxPlays:options.maxPlays??500,model:modelVersion,...(options.empirical?{profileId:options.empirical.profileId}:{})}),seed:options.seed,inputsTimestamp:g.inputsTimestamp,finalState:state,completed:state.status==='FINAL',winner:state.status==='FINAL'?(differential>0?g.homeTeam:differential<0?g.awayTeam:null):null,totalPoints:state.scoreHome+state.scoreAway,homeScoreDifferential:differential,teams,drives,pace:{clockSeconds:seconds,operationalSeconds,averageDriveSeconds:drives.length?seconds/drives.length:0},...(options.debugTrace?{trace}:{})};
}
