import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {simulateGameV2,openingState,applyOutcome,DEFAULT_TEAM} from '../src/simulation/v2/engine.ts';
import {validateProfile,empiricalPass,empiricalYards} from '../src/simulation/v2/empirical.ts';import {random} from '../public/simulation/random.js';
const game=JSON.parse(readFileSync(new URL('./fixtures/v2/matchup.json',import.meta.url))),profile=JSON.parse(readFileSync(new URL('../public/drive-lab/empirical.json',import.meta.url)));
test('empirical training season is separated and reproducible',()=>{assert.equal(profile.trainingSeason,2024);validateProfile(profile);const a=simulateGameV2(game,{seed:'b-check',empirical:profile,debugTrace:true});assert.deepEqual(a,simulateGameV2(game,{seed:'b-check',empirical:profile,debugTrace:true}));assert.equal(a.modelVersion,'V2.0-B-experimental');assert.equal(a.pace.clockSeconds,3600);assert.notEqual(a.runId,simulateGameV2(game,{seed:'b-check'}).runId);});
test('empirical histogram sampling and malformed profiles',()=>{const rng=random('hist');const support=new Set(profile.yards.run.map(x=>x[0]));for(let i=0;i<100;i++)assert.ok(support.has(empiricalYards('run',profile,rng)));assert.throws(()=>validateProfile({...profile,yards:{run:[[1,-1]],complete:[[1,1]]}}));assert.throws(()=>validateProfile({...profile,calls:{all:{probability:NaN}}}));});
test('conditional play rates back off with bounded team adjustment',()=>{const s={...openingState(game),distance:2,down:3};const p={...profile,calls:{all:{count:100,probability:.4}}};assert.equal(empiricalPass(s,{...DEFAULT_TEAM,passRate:p.baselinePassRate},p),.4);assert.ok(empiricalPass(s,{...DEFAULT_TEAM,passRate:1},p)<=.95);});
test('fourth down at goal line on final play retains a valid terminal distance',()=>{const s={...openingState(game),field:95,distance:5,down:4,quarter:4,clock:1};const r=applyOutcome(s,{playType:'RUN',resultType:'RUN',yards:3,duration:6});assert.equal(r.state.status,'FINAL');assert.equal(r.state.distance,2);assert.equal(r.driveResult,'DOWNS');});
test('empirical seed sweep conserves drives and regulation time',()=>{for(let i=0;i<200;i++){const r=simulateGameV2(game,{seed:`sweep:${i}`,empirical:profile});assert.ok(r.completed);assert.equal(r.pace.clockSeconds,3600);assert.equal(r.drives.reduce((n,d)=>n+d.seconds,0),3600);}});
