import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {runSlateSimulation,validateLineup,dkScore,applyOverrides} from '../public/simulation/engine.js';
import {summarize,correlation,compareRuns,calibrationReport} from '../public/simulation/statistics.js';
import {persistSimulation} from '../public/simulation/persistence.js';
const full=JSON.parse(readFileSync('public/simulation/slates/151307.json','utf8'));
const fixture=structuredClone(full);fixture.games=full.games.slice(0,2);fixture.players=full.players.filter(p=>fixture.games.some(g=>g.game_id===p.game_id));
const options={includeStacks:false,generateCandidates:false};
test('deterministic seeded runs, summaries only, distinct seed',()=>{const a=runSlateSimulation(fixture,100,'repeat',options),b=runSlateSimulation(fixture,100,'repeat',options);assert.deepEqual(a,b);assert.notEqual(a.players[0].mean,runSlateSimulation(fixture,100,'other',options).players[0].mean);assert.ok(!JSON.stringify(a).includes('"draws"'));});
test('allocation conservation, integer TDs, yard reconciliation, script and QB catcher correlation',()=>{
 const qb=fixture.players.filter(p=>p.position==='QB').sort((a,b)=>b.inputs.pass_attempts-a.inputs.pass_attempts)[0],wr=fixture.players.filter(p=>p.team===qb.team&&p.position==='WR').sort((a,b)=>b.inputs.targets-a.inputs.targets)[0];
 const qs=[],ws=[],lead=[],pass=[];runSlateSimulation(fixture,5000,'accounting',{...options,onDraw:d=>{for(const t of Object.values(d.teams)){assert.equal(t.plays,t.passAttempts+t.rushAttempts);assert.equal(t.carries,t.rushAttempts);assert.ok(t.targets<=t.passAttempts);assert.equal(t.passingYards,t.receivingYards);assert.equal(t.touchdowns,t.passTds+t.rushTds);assert.ok(Number.isInteger(t.touchdowns));}
 for(const s of d.players.values()){assert.ok(s.receiving_tds<=s.receptions);assert.ok(s.rushing_tds<=s.carries);assert.ok(Number.isInteger(s.receiving_tds));}
 if(d.players.has(qb.player_id)){qs.push(d.players.get(qb.player_id).passing_yards);ws.push(d.players.get(wr.player_id).receiving_yards);lead.push(d.teams[qb.team].script);pass.push(d.teams[qb.team].passAttempts/d.teams[qb.team].plays);}}});assert.ok(correlation(qs,ws)>.3);assert.ok(correlation(lead,pass)<-.3);
});
test('yardage bonuses trigger only at actual thresholds',()=>{const s={passing_yards:299,passing_tds:0,interceptions:0,rushing_yards:99,rushing_tds:0,receiving_yards:99,receiving_tds:0,receptions:0,fumbles_lost:0};for(const [key,delta] of [['passing_yards',3.04],['rushing_yards',3.1],['receiving_yards',3.1]])assert.ok(Math.abs(dkScore({...s,[key]:s[key]+1},'QB')-dkScore(s,'QB')-delta)<1e-8);});
test('OUT removes outcomes, redistributes volume, baseline remains immutable',()=>{const target=fixture.players.filter(p=>p.position==='WR').sort((a,b)=>b.inputs.targets-a.inputs.targets)[0];const original=JSON.stringify(fixture),a=runSlateSimulation(fixture,3000,'out',options),b=runSlateSimulation(fixture,3000,'out',{...options,overrides:[{target:'player',id:target.player_id,parameter:'out',value:true}]});assert.equal(b.players.find(p=>p.player_id===target.player_id).max,0);const other=p=>p.team===target.team&&p.player_id!==target.player_id;assert.ok(b.players.filter(other).reduce((s,p)=>s+p.mean_targets,0)>a.players.filter(other).reduce((s,p)=>s+p.mean_targets,0));assert.equal(JSON.stringify(fixture),original);const delta=compareRuns(a,b).players.find(p=>p.player_id===target.player_id);assert.ok(delta.mean_delta<0);});
test('game total increases scoring, pass-rate and workload scenarios change opportunity',()=>{const team=fixture.games[0].home,rb=fixture.players.filter(p=>p.team===team&&p.position==='RB').sort((a,b)=>b.inputs.carries-a.inputs.carries)[0],base=runSlateSimulation(fixture,2000,42,options);const scenario=runSlateSimulation(fixture,2000,42,{...options,overrides:[{target:'game',id:fixture.games[0].game_id,parameter:'total',value:65},{target:'team',id:team,parameter:'pass_rate',value:.8},{target:'player',id:rb.player_id,parameter:'limited',value:.1}]});assert.ok(scenario.teams.find(t=>t.team===team).mean_points>base.teams.find(t=>t.team===team).mean_points);assert.ok(scenario.teams.find(t=>t.team===team).pass_rate>base.teams.find(t=>t.team===team).pass_rate);assert.ok(scenario.players.find(p=>p.player_id===rb.player_id).mean_carries<base.players.find(p=>p.player_id===rb.player_id).mean_carries);});
test('legal candidates and stack combined means, manual lineup',()=>{const r=runSlateSimulation(full,100,4,{retainDraws:true});assert.ok(r.lineups.length>=4);for(const l of r.lineups)validateLineup(l.player_ids,full.players);for(const s of r.stacks){const total=s.player_ids.reduce((v,id)=>v+r.players.find(p=>p.player_id===id).mean,0);assert.ok(Math.abs(total-s.mean)<.0001);assert.ok(s.p95>=s.p90);}assert.throws(()=>validateLineup(Array(9).fill(full.players[0].player_id),full.players));const m=runSlateSimulation(full,100,4,{...options,lineups:[r.lineups[0].player_ids]});assert.ok(Math.abs(m.lineups[0].mean-r.lineups[0].mean)<.0001);});
test('percentiles, population variance and strict exceedance',()=>{const s=summarize([0,10,20,30],{salary:5000,projection:10,thresholds:[20]});assert.equal(s.median,15);assert.ok(Math.abs(s.p10-3)<1e-10);assert.equal(s.probability_exceed_projection,50);assert.equal(s.probabilities[20],25);assert.equal(s.histogram.reduce((s,b)=>s+b.count,0),4);});
test('invalid inputs and conflicting scenarios rejected',()=>{assert.throws(()=>runSlateSimulation(fixture,0,1));assert.throws(()=>runSlateSimulation(fixture,200001,1));assert.throws(()=>applyOverrides(fixture,[{target:'team',id:'BOGUS',parameter:'pass_rate',value:.5}]));const players=fixture.players.filter(p=>p.team===fixture.players[0].team).slice(0,2);assert.throws(()=>applyOverrides(fixture,players.map(p=>({target:'player',id:p.player_id,parameter:'target_share',value:.8}))));});
test('atomic summary persistence and immutable run/player records',async()=>{const db=new DatabaseSync(':memory:');db.exec(readFileSync('migrations/0008_dfs_simulations.sql','utf8'));const r=runSlateSimulation(fixture,10,1,options);const wrapper={prepare:q=>({bind:(...a)=>({run:()=>db.prepare(q).run(...a)})})};await persistSimulation(wrapper,r);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM dfs_simulation_player_summaries').get().n,fixture.players.length);assert.deepEqual(JSON.parse(db.prepare('SELECT summary_json FROM dfs_simulation_runs').get().summary_json),r);await assert.rejects(persistSimulation(wrapper,r));assert.throws(()=>db.exec('UPDATE dfs_simulation_runs SET seed="new"'));assert.throws(()=>db.exec('DELETE FROM dfs_simulation_player_summaries'));db.close();});
test('held-out calibration refuses overlapping windows',()=>{assert.throws(()=>calibrationReport([],{trainingWindow:{end:'2025-10-01'},evaluationWindow:{start:'2025-09-01'}}));});
test('shared shootout environment and DST opposition produce expected correlation directions',()=>{const home=fixture.games[0].home,away=fixture.games[0].away;const qb=fixture.players.filter(p=>p.team===home&&p.position==='QB').sort((a,b)=>b.inputs.pass_attempts-a.inputs.pass_attempts)[0],wr=fixture.players.filter(p=>p.team===away&&p.position==='WR').sort((a,b)=>b.inputs.targets-a.inputs.targets)[0],dst=fixture.players.find(p=>p.team===home&&p.position==='DST');const a=[],b=[],def=[],points=[];runSlateSimulation(fixture,6000,'correlation',{...options,onDraw:d=>{if(d.game_id!==fixture.games[0].game_id)return;a.push(d.players.get(qb.player_id).passing_yards);b.push(d.players.get(wr.player_id).receiving_yards);def.push(dkScore(d.players.get(dst.player_id),'DST'));points.push(d.teams[away].points);}});assert.ok(correlation(a,b)>0);assert.ok(correlation(def,points)<-.25);});
test('fixed share, zero share, carries multiplier and snap-share scenarios',()=>{const p=fixture.players.filter(p=>p.position==='RB').sort((a,b)=>b.inputs.carries-a.inputs.carries)[0];const base=runSlateSimulation(fixture,2000,'shares',options);for(const [parameter,value] of [['rush_share',0],['snap_share',0],['limited',0]]){const r=runSlateSimulation(fixture,2000,'shares',{...options,overrides:[{target:'player',id:p.player_id,parameter,value}]});assert.equal(r.players.find(x=>x.player_id===p.player_id).mean_carries,0);}const r=runSlateSimulation(fixture,2000,'shares',{...options,overrides:[{target:'player',id:p.player_id,parameter:'carries_multiplier',value:1.2}]});assert.ok(r.players.find(x=>x.player_id===p.player_id).mean_carries>base.players.find(x=>x.player_id===p.player_id).mean_carries);});
test('stack pool covers teams and all requested stack forms',()=>{const r=runSlateSimulation(full,10,9);for(const type of ['QB+WR','QB+TE','QB+WR+WR','QB+WR+TE','QB+catcher+opponent'])assert.ok(r.stacks.some(s=>s.type===type));assert.equal(new Set(r.stacks.map(s=>s.team)).size,24);});
test('historical calibration reports actual held-out metrics and rejects leakage',()=>{const data={trainingWindow:{start:'2024-09-01',end:'2024-12-31'},evaluationWindow:{start:'2025-09-01',end:'2025-12-31'}};const row={player_id:'1',game_id:'game1',position:'QB',game_date:'2025-09-10',pregame_as_of:'2025-09-09',mean:15,actual:20,p10:5,p90:25,stddev:6};const result=calibrationReport([row],data);assert.equal(result.overall.mae,5);assert.equal(result.by_position.QB.count,1);assert.throws(()=>calibrationReport([{...row,pregame_as_of:'2025-09-11'}],data));});
test('competing fixed-total opportunities have negative covariance',async()=>{const {random,allocate}=await import('../public/simulation/random.js');const rng=random('competition'),a=[],b=[];for(let i=0;i<3000;i++){const rows=allocate(35,[.5,.5],rng);a.push(rows[0]);b.push(rows[1]);}assert.ok(correlation(a,b)<-.99);});
test('limited QB transfers unfilled attempts to a residual QB; unsupported position parameters fail',()=>{const input=structuredClone(fixture);const qb=input.players.filter(p=>p.position==='QB').sort((a,b)=>b.inputs.pass_attempts-a.inputs.pass_attempts)[0];input.players=input.players.filter(p=>p.position!=='QB'||p.team!==qb.team||p.player_id===qb.player_id);let attempts=0;runSlateSimulation(input,1000,7,{...options,overrides:[{target:'player',id:qb.player_id,parameter:'limited',value:.5}],onDraw:d=>{if(d.players.has(qb.player_id))attempts+=d.players.get(qb.player_id).pass_attempts;}});assert.ok(attempts/1000<qb.inputs.pass_attempts*.75);const dst=input.players.find(p=>p.position==='DST');assert.throws(()=>applyOverrides(input,[{target:'player',id:dst.player_id,parameter:'limited',value:.5}]));});
