import test from 'node:test';
import assert from 'node:assert/strict';
import {propTable} from '../public/ui/props-view.js';
const records=[{playerId:'a',playerName:'Player One',playerTeam:'DET',position:'WR',opponentTeam:'NO',marketKey:'receptions',marketLabel:'receptions',line:4.5,recentAverage:5,confidence:72,direction:'over'}, {playerId:'b',playerName:'Player Two',playerTeam:'NO',position:'RB',opponentTeam:'DET',marketKey:'rushing_yards',marketLabel:'rushing yards',line:55,recentAverage:51,confidence:68,direction:'under'}];
test('prop market filters include receptions under receiving and combine search/team filters',()=>{assert.equal(propTable(records,{market:'receiving'}).count,1);assert.equal(propTable(records,{market:'rushing'}).count,1);assert.equal(propTable(records,{market:'receiving',team:'NO'}).count,0);assert.equal(propTable(records,{search:'Player One',team:'DET'}).count,1);});
test('prop table escapes source strings and does not turn confidence into probabilities',()=>{const result=propTable([{...records[0],playerName:'<script>bad</script>',sportsbook:'<b>book</b>'}]);assert.ok(result.html.includes('&lt;script&gt;'));assert.ok(!result.html.includes('<script>'));assert.ok(result.html.includes('72 / 100'));assert.ok(!result.html.replace(/<[^>]*>/g,'').includes('72%'));assert.ok(result.html.includes('Recent avg.'));});
test('empty prop datasets have a visible empty state',()=>assert.match(propTable([]).html,/No props match/));

import {avatarGroup,confidenceMeter,histogramMarkers,stackPreview} from '../public/ui/components.js';
test('missing confidence stays unavailable and meter values are bounded',()=>{assert.equal(confidenceMeter(null),'—');assert.equal(confidenceMeter(undefined),'—');assert.match(confidenceMeter(120),/aria-valuenow="100"/);});
test('histogram markers use bin boundaries and omit unavailable sportsbook values',()=>{const html=histogramMarkers({histogram:[{from:0,to:10},{from:10,to:20}],final_projection:10,median:8,p25:4,p75:12,market_projection:null});assert.match(html,/left:50%/);assert.doesNotMatch(html,/Sportsbook/);assert.equal(histogramMarkers({histogram:[]}), '');});
test('avatar groups retain canonical identity and stack bring-backs use actual teams',()=>{const players=[{id:'1',player_name:'QB',team:'BUF',position:'QB'},{id:'2',player_name:'WR',team:'DET',position:'WR'}];assert.match(avatarGroup(players,1),/\+1/);assert.match(avatarGroup(players),/data-ui-player="1"/);assert.match(stackPreview(players),/Bring-back/);assert.doesNotMatch(stackPreview(players.slice(0,1)),/Bring-back/);});

import {mediaCandidates} from '../public/ui/player-media.js';
test('media resolves headshot, team logo, then initials without unsafe or duplicate URLs',()=>{const teams={BUF:{logo:'https://assets.test/buf.png'}},players={a:{headshot:'https://assets.test/a.png',team:'BUF'},b:{headshot:'javascript:bad',team:'BUF'}};assert.deepEqual(mediaCandidates({uiPlayer:'a'},players,teams),['https://assets.test/a.png','https://assets.test/buf.png']);assert.deepEqual(mediaCandidates({uiPlayer:'b'},players,teams),['https://assets.test/buf.png']);assert.deepEqual(mediaCandidates({uiPlayer:'unknown',playerTeam:'BUF'},players,teams),['https://assets.test/buf.png']);assert.deepEqual(mediaCandidates({uiTeam:'BUF'},players,teams),['https://assets.test/buf.png']);assert.deepEqual(mediaCandidates({uiPlayer:'unknown'},players,teams),[]);});
