import {fingerprint} from '../../public/simulation/random.js';
import type {AvailabilitySnapshot,AvailabilityConfig} from '../simulation/v2/availability.ts';
import {participation} from '../simulation/v2/availability.ts';
export type Engine='v1'|'base'|'personnel';
export interface Override {key:string;value:number;}
export interface PlayerOverride {playerId:string;playProbability:number;workloadIfActive:number;}
export interface Scenario {version:1;scenarioId:string;name:string;gameId:string;engine:Engine;preset:string;playerOverrides:PlayerOverride[];teamOverrides:Override[];coachingOverrides:Override[];matchupOverrides:Override[];assumptionOverrides:Override[];createdAt:string;snapshots:Record<string,string>;}
export interface Assumption {key:string;scope:'game'|'team'|'unit'|'player'|'coaching';label:string;units:string;source:string;sourceTimestamp:string|null;sampleSize:number|null;confidence:string;defaultValue:number;override:number|null;effectiveValue:number;bounds:[number,number];normalRange:[number,number]|null;modelVersion:string;engines:Engine[];warnings:string[];}
export type Registry=Record<string,Assumption>;
export function emptyScenario(gameId:string,engine:Engine='personnel',createdAt=new Date().toISOString()):Scenario{return {version:1,scenarioId:'scenario-'+fingerprint([gameId,createdAt]),name:'Research scenario',gameId,engine,preset:'balanced',playerOverrides:[],teamOverrides:[],coachingOverrides:[],matchupOverrides:[],assumptionOverrides:[],createdAt,snapshots:{}};}
export function freshness(at:string|null,now:string,status='ok') {if(status!=='ok')return 'FAILED';const age=at?(Date.parse(now)-Date.parse(at))/3600000:Infinity;return !Number.isFinite(age)||age>24?'STALE':age>12?'AGING':'CURRENT';}
export function canonicalState(a:AvailabilitySnapshot,c:AvailabilityConfig,now:string){return Object.fromEntries(Object.values(a.players).map(p=>{const s=participation(p,c);const roster=p.status==='ACT'?'ACTIVE_ROSTER':p.availability.state==='IR/PUP'?'IR_PUP':p.availability.state==='SUSPENDED'?'SUSPENDED':p.status==='DEV'?'PRACTICE_SQUAD':p.status==='CUT'?'RELEASED':'UNKNOWN';const practice=({'Full Participation in Practice':'FULL','Limited Participation in Practice':'LIMITED','Did Not Participate In Practice':'DNP'} as Record<string,string>)[p.availability.practice_status??'']??'NOT_LISTED';return [p.player_id,{playerId:p.player_id,name:p.name,team:p.team,position:p.position,official:{roster,practice,game:p.availability.game_status?.toUpperCase()||(['OUT','INACTIVE'].includes(p.availability.state)?p.availability.state:'UNKNOWN'),source:p.availability.source,fetchedAt:p.availability.updated_at,sourcePublishedAt:(p.availability as any).source_published_at??null,season:(a as any).season??null,week:(a as any).week??null,injurySnapshot:a.snapshot_id,freshness:freshness(p.availability.updated_at,now,(a as any).source_status??'ok')},model:{playProbability:s.active_probability,workloadIfActive:s.workload_multiplier,basis:s.basis},effective:{playProbability:s.active_probability,workloadIfActive:s.workload_multiplier,participation:s.participation}}];}));}
export function validateScenario(s:Scenario){if(!s||!['playerOverrides','teamOverrides','coachingOverrides','matchupOverrides','assumptionOverrides'].every(k=>Array.isArray((s as any)[k])))throw Error('Scenario arrays required');if(s.version!==1||!['v1','base','personnel'].includes(s.engine)||!s.gameId||!s.name||s.name.length>100||!Number.isFinite(Date.parse(s.createdAt)))throw Error('Invalid scenario configuration');if(s.playerOverrides.length>150||new Set(s.playerOverrides.map(p=>p.playerId)).size!==s.playerOverrides.length)throw Error('Duplicate/too many player overrides');for(const p of s.playerOverrides)if(!p.playerId||[p.playProbability,p.workloadIfActive].some(v=>!Number.isFinite(v)||v<0||v>1))throw Error('Availability probabilities/workloads must be 0–100%');const rows=[...s.teamOverrides,...s.coachingOverrides,...s.matchupOverrides,...s.assumptionOverrides];if(rows.length>300||new Set(rows.map(x=>x.key)).size!==rows.length||rows.some(x=>!x.key||!Number.isFinite(x.value)))throw Error('Invalid/duplicate assumption override');return s;}
export function resolveRegistry(registry:Registry,s:Scenario):Registry{validateScenario(s);const r=structuredClone(registry);for(const o of [...s.teamOverrides,...s.coachingOverrides,...s.matchupOverrides,...s.assumptionOverrides]){const a=r[o.key];if(!a)throw Error(`Unknown assumption ${o.key}`);if(!a.engines.includes(s.engine))throw Error(`${a.label} is not implemented by ${s.engine}`);if(o.key.endsWith('fourth_down_distance')&&!Number.isInteger(o.value))throw Error('Fourth-down distance must be whole yards');if(o.value<a.bounds[0]||o.value>a.bounds[1])throw Error(`${a.label} outside mathematical/safety bounds`);a.override=o.value;a.effectiveValue=o.value;if(a.normalRange&&(o.value<a.normalRange[0]||o.value>a.normalRange[1]))a.warnings.push('Outside reference range (not a measured confidence interval)');}return r;}
export function modelFingerprint(s:Scenario,registry:Registry,seed:string,count:number,snapshots:Record<string,string>){validateScenario(s);if(!seed||!Number.isInteger(count)||count<1||count>10000)throw Error('Invalid seed/count');const ordered=(rows:Override[])=>[...rows].sort((a,b)=>a.key.localeCompare(b.key));const material={version:s.version,engine:s.engine,preset:s.preset,gameId:s.gameId,playerOverrides:[...s.playerOverrides].sort((a,b)=>a.playerId.localeCompare(b.playerId)),overrides:ordered([...s.teamOverrides,...s.coachingOverrides,...s.matchupOverrides,...s.assumptionOverrides]),effective:Object.fromEntries(Object.entries(registry).sort(([a],[b])=>a.localeCompare(b)).map(([k,a])=>[k,a.effectiveValue])),snapshots:Object.fromEntries(Object.entries(snapshots).sort(([a],[b])=>a.localeCompare(b))),seed,count};return 'model-'+fingerprint(material);}
export function assumption(key:string,scope:Assumption['scope'],value:number,units:string,source:string,at:string|null,bounds:[number,number],engines:Engine[],sampleSize:number|null=null,normalRange:[number,number]|null=null):Assumption{return {key,scope,label:key.replaceAll('_',' '),units,source,sourceTimestamp:at,sampleSize,confidence:sampleSize===null?'explicit prior / unverified coaching attribution':sampleSize<30?'low sample; stabilized':'stabilized historical context',defaultValue:value,override:null,effectiveValue:value,bounds,normalRange,modelVersion:'unified-1',engines,warnings:[]};}
