// @ts-expect-error Shared existing JS summarizer.
import {summarize} from '../../public/simulation/statistics.js';
export const METRICS=['pass_attempts','passing_yards','passing_tds','rushing_yards','receiving_yards','receptions','targets','carries','rushing_tds','receiving_tds','interceptions','fumbles_lost'] as const;
export class DistributionCollector {
 players:Record<string,Record<string,number[]>>={};scores:Record<string,number[]>={};team:Record<string,Record<string,number[]>>={};
 addPlayer(id:string,stats:Record<string,number>){const p=this.players[id]??={};for(const k of METRICS)(p[k]??=[]).push(stats[k]??0);(p.touchdowns??=[]).push((stats.rushing_tds??0)+(stats.receiving_tds??0));}
 addTeam(id:string,stats:Record<string,number>){const t=this.team[id]??={};for(const [k,v]of Object.entries(stats))if(Number.isFinite(v))(t[k]??=[]).push(v);}
 player(id:string){const p=this.players[id];if(!p)return {stats:{},pmf:{}};return {stats:Object.fromEntries(Object.entries(p).map(([k,v])=>[k,summarize(v)])),pmf:Object.fromEntries(Object.entries(p).map(([k,values])=>{const counts=new Map<number,number>();for(const v of values)counts.set(v,(counts.get(v)??0)+1);return [k,[...counts].sort(([a],[b])=>a-b)];}))};}
}
export function evaluateProp(player:{stats:Record<string,any>;pmf:Record<string,number[][]>},metric:string,line:number,americanOdds:number|null=null){if(!Number.isFinite(line)||line<0||!player.pmf[metric])throw Error('Unsupported prop or invalid line');if(americanOdds!==null&&(!Number.isFinite(americanOdds)||Math.abs(americanOdds)<100))throw Error('Invalid American odds');const rows=player.pmf[metric];const n=rows.reduce((s,[,v])=>s+v,0);const p=(test:(x:number)=>boolean)=>rows.filter(([x])=>test(x)).reduce((s,[,v])=>s+v,0)/n;const over=p(x=>x>line),under=p(x=>x<line),push=p(x=>x===line);const implied=americanOdds===null?null:americanOdds<0?-americanOdds/(-americanOdds+100):100/(americanOdds+100);return {metric,line,mean:player.stats[metric].mean,median:player.stats[metric].median,over,under,push,impliedProbability:implied,conditionalOver:push<1?over/(1-push):null,edge:implied!==null&&push<1?over/(1-push)-implied:null,warning:'Simulation disagreement, not a betting recommendation. Price is not de-vigged; integer-line edges condition on no push.'};}
