import {assumption,resolveRegistry,modelFingerprint,canonicalState,type Scenario,type Registry} from './contract.ts';
import {prepareAvailability,type AvailabilitySnapshot,type AvailabilityConfig,type Scenarios} from '../simulation/v2/availability.ts';
import type {PlayerSnapshot,PersonnelSnapshot,InfluenceConfig} from '../simulation/v2/player-types.ts';
import type {GameInputV2,CoachingInput} from '../simulation/v2/engine.ts';
import type {EmpiricalProfile} from '../simulation/v2/empirical.ts';
import {runFantasyBulk} from '../simulation/v2/player-bulk.ts';
import {fingerprint} from '../../public/simulation/random.js';
import {DistributionCollector} from './outputs.ts';
import {runSlateSimulation} from '../../public/simulation/engine.js';
// @ts-expect-error Existing shared JS scorer.
import {summarize} from '../../public/simulation/statistics.js';
export interface Sources {game:GameInputV2&{market?:any};players:PlayerSnapshot;personnel:PersonnelSnapshot;availability:AvailabilitySnapshot;availabilityConfig:AvailabilityConfig;influence:InfluenceConfig;empirical:EmpiricalProfile;v1:any;presets:{version:string;presets:Record<string,{name:string;recentShareWeight:number;personnelInfluence:number;marketWeight:number}>};}
export function registryFor(x:Sources):Registry{
 const r:Registry={};const add=(...args:Parameters<typeof assumption>)=>{const a=assumption(...args);r[a.key]=a;};const all=['v1','base','personnel'] as const;
 for(const tm of [x.game.homeTeam,x.game.awayTeam]){const t=tm===x.game.homeTeam?x.game.homeTeamInputs:x.game.awayTeamInputs;
  add(`${tm}.neutral_pass_rate`,'coaching',t.passRate,'fraction','Recency team PBP + league stabilization; play caller not verified',x.players.as_of,[0,1],[...all],null,[.25,.85]);
  add(`${tm}.prior_system_weight`,'coaching',1,'history weight','Engineer coaching-change uncertainty: blend prior team tendency with league baseline; named coach history unavailable',x.players.as_of,[0,1],[...all],null,[0,1]);
  add(`${tm}.pace_factor`,'coaching',1,'seconds multiplier','Empirical snap-gap pace; no verified coach attribution',x.players.as_of,[.3,1.7],['base','personnel'],x.empirical.pace.normal?.count??null,[.7,1.3]);
  for(const [name,state]of [['leading_pass_rate','lead'],['trailing_pass_rate','trail']] as const){const cells=Object.entries(x.empirical.calls).filter(([k])=>k.endsWith('|'+state));const n=cells.reduce((s,[,v])=>s+v.count,0);add(`${tm}.${name}`,'coaching',n?cells.reduce((s,[,v])=>s+v.count*v.probability,0)/n:t.passRate,'fraction','Stabilized league late-game score-state cells; team/coach proxy',x.players.as_of,[0,1],['base','personnel'],n,[.2,.9]);}
  add(`${tm}.redzone_pass_rate`,'coaching',t.passRate,'fraction','No separate fitted coach red-zone model; neutral-rate prior',x.players.as_of,[0,1],['base','personnel'],null,[.2,.85]);
  add(`${tm}.fourth_down_distance`,'coaching',2,'yards','Fourth-down decision-rule prior',null,[0,10],['base','personnel'],null,[0,4]);
  for(const key of ['pass_protection','run_block','pass_rush','run_front','secondary','receiving'])add(`${tm}.${key}_factor`,'unit',1,'rating multiplier','Scenario-active Madden composite; does not fill missing evidence',x.availability.as_of,[0,2],['personnel'],null,[.8,1.2]);
  for(const p of x.players.teams[tm].players)for(const key of ['normal_carry','normal_target','redzone_carry','redzone_target','goal_carry','goal_target'])if(p.position!=='QB'||key.endsWith('carry'))add(`${p.player_id}.${key}`,'player',p.shares[key],'team share','Recency PBP / role and projection fallback',x.players.as_of,[0,1],key.startsWith('normal')?[...all]:['base','personnel']);
 }
 add('game.yardage_factor','game',1,'yardage multiplier','Football efficiency sensitivity prior',x.players.as_of,[.25,2],[...all],null,[.8,1.2]);
 add('game.turnover_factor','game',1,'rate multiplier','Empirical interception/fumble rates',x.players.as_of,[0,3],['base','personnel'],null,[.5,1.5]);
 return r;
}
function reconcileOverrides(players:PlayerSnapshot,r:Registry,teams:string[]){for(const tm of teams)for(const context of ['normal','redzone','goal'])for(const kind of ['carry','target']){const key=context+'_'+kind,ps=players.teams[tm].players,fixed=ps.filter(p=>r[`${p.player_id}.${key}`]?.override!==null&&r[`${p.player_id}.${key}`]?.override!==undefined),fixedTotal=fixed.reduce((s,p)=>s+r[`${p.player_id}.${key}`].effectiveValue,0);if(fixedTotal>1+1e-8)throw Error('Fixed opportunity shares exceed 100%');if(!fixed.length)continue;const other=ps.filter(p=>!fixed.includes(p)),mass=other.reduce((s,p)=>s+p.shares[key],0);if(!mass&&fixedTotal<1)throw Error('No supported remaining workload recipients');for(const p of fixed)p.shares[key]=r[`${p.player_id}.${key}`].effectiveValue;for(const p of other)p.shares[key]=mass?p.shares[key]/mass*(1-fixedTotal):0;}}
export function prepareModel(x:Sources,s:Scenario,now:string){
 if(s.gameId!==x.game.gameId)throw Error('Scenario/game mismatch');const preset=x.presets.presets[s.preset];if(!preset)throw Error('Unknown preset');const players=structuredClone(x.players),teams=[x.game.homeTeam,x.game.awayTeam];
 for(const tm of teams)for(const key of Object.keys(players.teams[tm].players[0].shares)){const ps=players.teams[tm].players;let total=0;for(const p of ps){const recent=(p as any).recent_shares?.[key];if(Number.isFinite(recent))p.shares[key]=p.shares[key]*(1-preset.recentShareWeight)+recent*preset.recentShareWeight;total+=p.shares[key];}if(total)for(const p of ps)p.shares[key]/=total;}
 const registry=resolveRegistry(registryFor({...x,players}),s);reconcileOverrides(players,registry,teams);for(const tm of teams)for(const q of players.teams[tm].players)for(const [key,value]of Object.entries(q.shares)){const a=registry[`${q.player_id}.${key}`];if(a)a.effectiveValue=value;}for(const o of s.playerOverrides)if(!x.availability.players[o.playerId]||!teams.includes(x.availability.players[o.playerId].team))throw Error('Player override is outside this matchup');const scenario:Scenarios={};for(const o of s.playerOverrides)scenario[o.playerId]={state:o.workloadIfActive===1?'ACTIVE':'LIMITED',playProbability:o.playProbability,workload:o.workloadIfActive};
 const prepared=prepareAvailability(players,x.personnel,x.availability,x.availabilityConfig,x.influence,teams,scenario,now);
 for(const tm of teams)for(const key of ['pass_protection','run_block','pass_rush','run_front','secondary','receiving']){const u=prepared.personnel.units[tm][key];if(u?.rating!=null)u.rating=Math.max(0,Math.min(99,u.rating*registry[`${tm}.${key}_factor`].effectiveValue));}
 const game=structuredClone(x.game),coaching:Record<string,CoachingInput>={};
 for(const tm of teams){const t=tm===game.homeTeam?game.homeTeamInputs:game.awayTeamInputs;const historyWeight=registry[`${tm}.prior_system_weight`].effectiveValue;t.passRate=historyWeight*registry[`${tm}.neutral_pass_rate`].effectiveValue+(1-historyWeight)*x.empirical.baselinePassRate;for(const rate of ['interceptionRate','fumbleRate'] as const)if(t[rate]!==undefined)t[rate]=Math.min(1,t[rate]!*registry['game.turnover_factor'].effectiveValue);coaching[tm]={paceFactor:registry[`${tm}.pace_factor`].effectiveValue};for(const [key,field]of [['leading_pass_rate','leadingPassRate'],['trailing_pass_rate','trailingPassRate'],['redzone_pass_rate','redzonePassRate'],['fourth_down_distance','fourthGoDistance']] as const)if(registry[`${tm}.${key}`].override!==null)coaching[tm][field]=registry[`${tm}.${key}`].effectiveValue;}
 const empirical=structuredClone(x.empirical);const market=game.market?.total;const anchored=Number.isFinite(market)?1+preset.marketWeight*(Math.max(.7,Math.min(1.3,market/44))-1):1;const factor=registry['game.yardage_factor'].effectiveValue*anchored;for(const kind of ['run','complete'])empirical.yards[kind]=empirical.yards[kind].map(([v,n])=>[Math.max(-99,Math.min(99,Math.round(v*factor))),n]);
 const official=canonicalState(x.availability,x.availabilityConfig,now);for(const [id,v]of Object.entries(prepared.states))if(official[id])official[id].effective={playProbability:v.active_probability,workloadIfActive:v.workload_multiplier,participation:v.participation};return {prepared,registry,game,coaching,empirical,preset,efficiencyFactor:factor,official};
}
export function runModel(x:Sources,s:Scenario,seed:string,count:number,now=new Date().toISOString()){
 const p=prepareModel(x,s,now);const refs={injury:x.availability.snapshot_id,roster:x.availability.roster_snapshot,madden:x.players.madden_snapshot,players:x.players.snapshot_id,empirical:x.empirical.profileId,sportsbook:x.game.inputsTimestamp,presets:x.presets.version,sourceContent:fingerprint(x)};const fp=modelFingerprint(s,p.registry,seed,count,refs),collector=new DistributionCollector();let playerRows:any[],teamRows:any,gameOutput:any,raw:any;
 if(s.engine!=='v1'){
  raw=runFantasyBulk(p.game,{seed,engine:s.engine,influence:s.engine==='base'?0:p.preset.personnelInfluence,empirical:p.empirical,players:p.prepared.players,personnel:p.prepared.personnel,preparedAvailability:p.prepared,config:x.influence,coaching:p.coaching},count,undefined,r=>{for(const [id,b]of Object.entries(r.players))collector.addPlayer(id,b.stats as any);for(const [tm,t]of Object.entries(r.teams))collector.addTeam(tm,t as any);});
  playerRows=raw.players.map((row:any)=>({playerId:row.player.player_id,name:row.player.name,team:row.player.team,position:row.player.position,salary:row.player.salary,dk:row.dk,...collector.player(row.player.player_id),availability:p.prepared.states[row.player.player_id],workload:p.prepared.workload[row.player.team][row.player.player_id],value:row.player.salary?row.dk.mean/(row.player.salary/1000):null}));teamRows=raw.teams;gameOutput={home:raw.home,away:raw.away,total:raw.total,spread:raw.margin,plays:raw.plays*2,possessions:raw.possessions*2,pace:null};
 }else{
  const source=structuredClone(x.v1);const game=source.games.find((g:any)=>g.game_id===s.gameId);if(!game)throw Error('V1 source lacks this matchup');source.games=[game];source.players=source.players.filter((q:any)=>q.game_id===s.gameId&&q.position!=='DST');source.original_players=structuredClone(source.players);source.team_overrides={};
  for(const tm of [x.game.homeTeam,x.game.awayTeam]){const active=p.prepared.players.teams[tm];for(const live of active.players)if(!source.players.some((q:any)=>q.player_id===live.player_id)){const template=source.players.find((q:any)=>q.team===tm&&q.position===live.position);source.players.push({...(template?structuredClone(template):{}),player_id:live.player_id,player_name:live.name,team:tm,opponent:tm===game.home?game.away:game.home,game_id:s.gameId,position:live.position,salary:live.salary??1,adapter_salary_missing:!live.salary,inputs:template?structuredClone(template.inputs):{},quality_flags:['Replacement uses position/team efficiency prior; individual history unavailable']});}const original=source.players.filter((q:any)=>q.team===tm);const qbAttempts=source.original_players.filter((q:any)=>q.team===tm).reduce((sum:number,q:any)=>sum+(q.inputs?.pass_attempts||0),0)||35;source.team_overrides[tm]={pass_rate:p.registry[`${tm}.neutral_pass_rate`].effectiveValue};for(const q of original){const live=active.players.find(v=>v.player_id===q.player_id);q.active=!!live;if(!live)continue;q.workload_factor=1;q.target_share_delta=0;q.inputs??={};q.inputs.rush_share=live.shares.normal_carry;q.inputs.target_share=live.shares.normal_target;q.fixed_rush_share=true;q.fixed_target_share=true;q.inputs.carries=28*live.shares.normal_carry;q.inputs.targets=qbAttempts*live.shares.normal_target;if(q.position==='QB')q.inputs.pass_attempts=qbAttempts*(p.prepared.qbShares[tm][q.player_id]??0);for(const key of ['passing_efficiency','receiving_efficiency','rushing_efficiency'])if(q.inputs[key])q.inputs[key]*=p.efficiencyFactor;}}
  const scores={home:[] as number[],away:[] as number[],total:[] as number[],spread:[] as number[]};raw=runSlateSimulation(source,count,seed,{includeStacks:false,generateCandidates:false,onDraw:(draw:any)=>{for(const [id,stats]of draw.players)collector.addPlayer(id,stats);const h=draw.teams[x.game.homeTeam].points,a=draw.teams[x.game.awayTeam].points;scores.home.push(h);scores.away.push(a);scores.total.push(h+a);scores.spread.push(h-a);for(const [tm,t]of Object.entries(draw.teams))collector.addTeam(tm,t as any);}});
  playerRows=raw.players.map((q:any)=>({playerId:q.player_id,name:q.player_name||q.name||x.availability.players[q.player_id]?.name,team:q.team,position:q.position,salary:q.adapter_salary_missing?null:q.salary,dk:Object.fromEntries(['mean','median','p75','p90','p95'].map(k=>[k,q[k]])),...collector.player(q.player_id),availability:p.prepared.states[q.player_id],workload:p.prepared.workload[q.team]?.[q.player_id],value:!q.adapter_salary_missing&&q.salary?q.mean/(q.salary/1000):null}));teamRows=Object.fromEntries(Object.entries(collector.team).map(([tm,t])=>[tm,Object.fromEntries(Object.entries(t).map(([k,v])=>[k,summarize(v).mean]))]));gameOutput={...Object.fromEntries(Object.entries(scores).map(([k,v])=>[k,summarize(v)])),plays:raw.teams.reduce((a:number,t:any)=>a+t.mean_plays,0),possessions:null,pace:null};
 }
 const commonTeams=Object.fromEntries(Object.entries(teamRows).map(([tm,t]:[string,any])=>[tm,{passAttempts:t.passAttempts??null,rushAttempts:t.rushingAttempts??t.rushAttempts??null,passYards:t.passingYards??null,rushYards:t.rushingYards??null,sacks:t.sacks??t.sacksAllowed??null,turnovers:t.turnovers??null,touchdowns:t.touchdowns??((t.passingTouchdowns!=null&&t.rushingTouchdowns!=null)?t.passingTouchdowns+t.rushingTouchdowns:null),distributions:Object.fromEntries(Object.entries(collector.team[tm]??{}).map(([k,v])=>[k,summarize(v)]))}]));
 return {version:1,fingerprint:fp,metadata:{engine:s.engine,preset:s.preset,scenario:structuredClone(s),seed,count,createdAt:now,snapshots:refs,availabilityStale:p.prepared.metadata.availability_stale,notes:['Experimental predictions; no contest-win claims','Unverified coach attribution; tendencies are historical team/league proxies',...(s.engine==='v1'?['V1 has residual allocation and no play-by-play personnel/score-state controls; unsupported controls are rejected']:[])]},assumptions:p.registry,official:Object.fromEntries(Object.entries(p.official).filter(([,v])=>[x.game.homeTeam,x.game.awayTeam].includes(v.team))),personnel:p.prepared.personnel.units,availability:p.prepared.states,workload:p.prepared.workload,game:gameOutput,teams:commonTeams,players:playerRows,rawEngineVersion:raw.metadata?.model_version??raw.model_version};
}
export function sensitivity(x:Sources,s:Scenario,key:string,values:number[],seed:string,count:number,now:string){if(values.length>7)throw Error('At most seven sensitivity points');return values.map(value=>{const scenario=structuredClone(s);for(const k of ['assumptionOverrides','teamOverrides','coachingOverrides','matchupOverrides'] as const)scenario[k]=scenario[k].filter(o=>o.key!==key);scenario.assumptionOverrides.push({key,value});return {value,result:runModel(x,scenario,seed,count,now)};});}
