#!/usr/bin/env node
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {dirname} from 'node:path';
import {runSlateSimulation,dkScore} from '../public/simulation/engine.js';
import {correlation,calibrationReport} from '../public/simulation/statistics.js';
export function fitPositions(rows){const out={};for(const pos of ['QB','RB','WR','TE']){const r=rows.filter(x=>x.position===pos);if(!r.length)continue;const bias=r.reduce((s,x)=>s+x.mean-x.actual,0)/r.length;const scale=Math.sqrt(r.reduce((s,x)=>s+(x.actual-(x.mean-bias))**2,0)/r.reduce((s,x)=>s+x.stddev**2,0));out[pos]={count:r.length,mean_bias:bias,stddev_scale:scale};}return out;}
export function adjust(row,fit){const f=fit[row.position];if(!f)throw Error('No training fit for position');const mean=row.mean-f.mean_bias;return {...row,mean,stddev:row.stddev*f.stddev_scale,p10:mean+(row.p10-row.mean)*f.stddev_scale,p75:mean+(row.p75-row.mean)*f.stddev_scale,p90:mean+(row.p90-row.mean)*f.stddev_scale};}
const metric=rows=>calibrationReport(rows,{trainingWindow:{start:'2024-01-01',end:'2025-03-01'},evaluationWindow:{start:'2025-08-01',end:'2026-03-01'}});
async function main(){const data=JSON.parse(readFileSync(process.argv[2])),count=Number(process.argv[4]||1000),training=[],evaluation=[],pairs=[];if(!Number.isInteger(count)||count<100||count>10000)throw Error('Diagnostic draw count must be 100–10000');
 for(const g of data.games){const paired=[];for(const t of [g.input.games[0].home,g.input.games[0].away]){const qb=g.input.players.filter(p=>p.team===t&&p.position==='QB').sort((a,b)=>b.inputs.pass_attempts-a.inputs.pass_attempts)[0],wr=g.input.players.filter(p=>p.team===t&&['WR','TE'].includes(p.position)).sort((a,b)=>b.inputs.targets-a.inputs.targets)[0];if(qb&&wr)paired.push({qb:qb.player_id,receiver:wr.player_id,x:[],y:[]});}
  const result=runSlateSimulation(g.input,count,'historical-core-v1',{generateCandidates:false,includeStacks:false,onDraw:d=>{for(const pair of paired){pair.x.push(dkScore(d.players.get(pair.qb),'QB'));pair.y.push(dkScore(d.players.get(pair.receiver),'WR'));}}});
  const rows=result.players.filter(p=>Number.isFinite(g.actuals[p.player_id])&&p.stddev>0).map(p=>({...p,actual:g.actuals[p.player_id],game_date:g.game_date,pregame_as_of:new Date(Date.parse(g.game_date)-86400000).toISOString()}));
  (g.split==='training'?training:evaluation).push(...rows);
  if(g.split==='evaluation')for(const pair of paired){const q=rows.find(r=>r.player_id===pair.qb),r=rows.find(r=>r.player_id===pair.receiver);if(q&&r)pairs.push({game_id:q.game_id,qb:q.player_id,receiver:r.player_id,simulated:correlation(pair.x,pair.y),qb_residual:(q.actual-q.mean)/q.stddev,receiver_residual:(r.actual-r.mean)/r.stddev});}
 }
 const fit=fitPositions(training),report={version:1,status:'exploratory_historical_diagnostic_not_production_calibration',generated_at:new Date().toISOString(),model:'nfl-dk-mc-foundation-v1.1',draws_per_game:count,game_count:data.games.length,training_cases:training.length,evaluation_cases:evaluation.length,identity_source:'NFLverse GSIS directly; no DraftKings identity join',source_hashes:data.source_hashes,exclusions:data.exclusions,training_fit:fit,before:metric(evaluation),after_training_only_adjustment:metric(evaluation.map(r=>adjust(r,fit))),qb_primary_receiver:{pair_games:pairs.length,unique_games:new Set(pairs.map(p=>p.game_id)).size,mean_simulated_correlation:pairs.length?pairs.reduce((s,p)=>s+p.simulated,0)/pairs.length:null,observed_standardized_residual_correlation:pairs.length>2?correlation(pairs.map(p=>p.qb_residual),pairs.map(p=>p.receiver_residual)):null},limitations:['Reconstructed prior-five same-team inputs, not archived ESPN forecasts or historical decision replay. Data downloaded today may include later corrections.','Artificial salary=1 only satisfies engine schema; no value, lineup or contest metrics are computed.','2024 trains bias/scale; 2025 is held out. Adjustments are experimental post-processing and are not deployed to current predictions.','Missing/no-opportunity actual rows are excluded, not zero-filled. Injury/limited status is unavailable; the cohort is conditional on observed offensive opportunity.','Core offensive scoring omits two-point/return/recovery touchdowns; no DST evaluation.','Fixed 44/0 market defaults, no coaching changes or injury context. Game dates provide chronological order; synthetic previous-day timestamps are diagnostic cutoffs, not capture receipts.','Correlation pools standardized residuals for the prior-history leading QB and WR/TE; repeated teams/games are dependent. No confidence interval or production promotion claim.']};mkdirSync(dirname(process.argv[3]),{recursive:true});writeFileSync(process.argv[3],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({games:report.game_count,training:training.length,evaluation:evaluation.length,before:report.before.overall,after:report.after_training_only_adjustment.overall,correlation:report.qb_primary_receiver}));
}
if(process.argv[1]?.endsWith('calibrate_historical_mc.mjs'))main().catch(e=>{console.error(e.stack);process.exitCode=1;});
