import {readFileSync,writeFileSync} from 'node:fs';
import {prepareAvailability} from '../src/simulation/v2/availability.ts';import {runFantasyBulk} from '../src/simulation/v2/player-bulk.ts';
const read=p=>JSON.parse(readFileSync(p)),players=read('public/drive-lab/players.json'),personnel=read('public/drive-lab/personnel.json'),availability=read('public/drive-lab/availability.json'),availabilityConfig=read('config/v2-availability.json'),config=read('config/v2-personnel.json'),empirical=read('public/drive-lab/live-empirical.json');
const teams={};for(const tm of Object.keys(players.teams).sort()){try{const p=prepareAvailability(players,personnel,availability,availabilityConfig,config,[tm]);const units=Object.fromEntries(Object.entries(p.personnel.units[tm]).filter(([key])=>!key.startsWith('secondary_')));teams[tm]={full:Object.values(units).filter(u=>u.scale===1).length,scaled:Object.values(units).filter(u=>u.scale>0&&u.scale<1).length,disabled:Object.values(units).filter(u=>!u.scale).length,units};}catch(e){teams[tm]={error:e.message};}}
const game=read('public/drive-lab/examples.json').games.find(g=>g.homeTeam==='DET'&&g.awayTeam==='NO'),id=players.teams.DET.players.find(p=>p.name==='Jahmyr Gibbs').player_id;
const opts={seed:'v2-d-review',engine:'personnel',influence:.5,players,personnel,availability,availabilityConfig,config,empirical,asOf:availability.as_of};
const baseline=runFantasyBulk(game,opts,10000),out=runFantasyBulk(game,{...opts,scenario:{[id]:{state:'OUT'}}},10000);
const compact=r=>({metadata:r.metadata,runtimeMs:r.runtimeMs,drawStorageBytes:r.drawStorageBytes,teamMeans:r.teams,modifiers:r.adjustments,units:r.availability.units.DET,workload:r.availability.workload.DET,players:r.players.filter(p=>p.player.team==='DET').map(p=>({id:p.player.player_id,name:p.player.name,dk:p.dk,mean_carries:p.stats.carries.mean,mean_targets:p.stats.targets.mean}))});
const report={version:'V2.0-D',availability_snapshot:availability.snapshot_id,coverage:availability.coverage,teams,scenario:{game,player_id:id,name:'Jahmyr Gibbs',note:'Hypothetical OUT sensitivity scenario; not a report that Gibbs is injured.',baseline:compact(baseline),out:compact(out)}};
writeFileSync('docs/simulation-v2-d-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({teams:Object.fromEntries(Object.entries(teams).map(([tm,t])=>[tm,{full:t.full,scaled:t.scaled,disabled:t.disabled,error:t.error}])),baselineMs:baseline.runtimeMs,outMs:out.runtimeMs,players:report.scenario.out.players.map(p=>({name:p.name,dk:p.dk.mean,carries:p.mean_carries,targets:p.mean_targets}))},null,2));
